package on2013_01.on2013_01_20_Codeforces_Round__162.A___Escape_from_Stones;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2013_01/on2013_01_20_Codeforces_Round__162/A___Escape_from_Stones/A - Escape from Stones.task"))
			Assert.fail();
	}
}
