package on2013_09.on2013_09_20_Codeforces_Round__201.C___Number_Transformation_II;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2013_09/on2013_09_20_Codeforces_Round__201/C___Number_Transformation_II/C - Number Transformation II.task"))
			Assert.fail();
	}
}
