package on2013_12.on2013_12_10_December_Challenge_2013.Petya_and_Sequence;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2013_12/on2013_12_10_December_Challenge_2013/Petya_and_Sequence/Petya and Sequence.task"))
			Assert.fail();
	}
}
