package on2012_12.on2012_12_16_Codeforces_Round__156.E___Lucky_Arrays;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2012_12/on2012_12_16_Codeforces_Round__156/E___Lucky_Arrays/E - Lucky Arrays.task"))
			Assert.fail();
	}
}
