package on2014_03.on2014_03_11_USACO_2014_March_Contest__Gold.Problem_2__Sabotage;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2014_03/on2014_03_11_USACO_2014_March_Contest__Gold/Problem_2__Sabotage/Problem 2. Sabotage.task"))
			Assert.fail();
	}
}
