package on2014_02.on2014_02_18_Codeforces_Round__230__Div__1_.C___Yet_Another_Number_Sequence;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2014_02/on2014_02_18_Codeforces_Round__230__Div__1_/C___Yet_Another_Number_Sequence/C - Yet Another Number Sequence.task"))
			Assert.fail();
	}
}
