package on2014_02.on2014_02_26_Codeforces_Round__232__Div__1_.E___On_Iteration_of_One_Well_Known_Function;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2014_02/on2014_02_26_Codeforces_Round__232__Div__1_/E___On_Iteration_of_One_Well_Known_Function/E - On Iteration of One Well-Known Function.task"))
			Assert.fail();
	}
}
